name: Release

on:
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Build Package
        run: |
          pdm build

      - name: Publish Package
        run: |
          pdm publish --no-build
